---
## Here we define the mapping between hosts and roles
## I'm also defining my group specific variables here.
- hosts: idm
  vars:
    ntp_servers:
    - '192.168.0.241'
    - '192.168.0.242'

    setup_dns: True

    idm_realm_name: "TEST.NIXGEEK.CO.UK"
    idm_domain_name: "test.nixgeek.co.uk"
    idm_ds_password: "password123"
    idm_admin_password: "password123"
    idm_install_command: "/usr/sbin/ipa-server-install"

  user: ansible
  roles:
  - common
  - idm